language: java

git:
  depth: 1

branches:
  except:
    - gh-pages
    - master_papyrus
  
cache:
  directories:
    - "$HOME/.m2/repository"

services:
  - xvfb
  
install: 
  - "" 
   
script: 
   - mvn clean package 
   - mvn clean verify -f test/pom.xml 
   - releng/scripts/deploy_pages.sh      
     
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_HUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: .gh-pages
  on:
    branch: master
  
after_failure:
  - cat /home/travis/build/Ericsson/papyrus-patches/test/uml/diagram/org.eclipse.papyrus.uml.diagram.sequence.test/target/work/data/.metadata/.log
  - cat /home/travis/build/Ericsson/papyrus-patches/test/uml/diagram/org.eclipse.papyrus.uml.diagram.sequence.test/target/work/configuration/*.log